[tool.black]
line-length = 120

[tool.ruff]
ignore = ["B008"]
line-length = 120
select = [
  "F",  # Pyflakes
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  #"C90",  # mccabe
  "I",  # isort
  #"N",  # pep8-naming
  "UP",  # pyupgrade
  #"YTT",  # flake8-2020
  #"S",  # flake8-bandit
  #"B",  # flake8-bugbear
  #"A",  # flake8-builtins
  "COM",  # flake8-commas
  "C40",  # flake8-comprehensions
  #"ISC",  # flake8-implicit-str-concat
  #"ICN",  # flake8-import-conventions
  #"G",  # flake8-logging-format
  #"PIE",  # flake8-pie
  #"PYI",  # flake8-pyi
  #"SLF",  # flake8-self
  "SIM",  # flake8-simplify
  #"TID",  # flake8-tidy-imports
  #"TCH",  # flake8-type-checking
  #"ARG",  # flake8-unused-arguments
  #"ERA",  # eradicate
  #"NPY",  # numpy
  #"RUF"  # ruff
]
show-fixes = true
show-source = true
target-version = "py38"

[tool.ruff.isort]
lines-after-imports = 2

[tool.ruff.mccabe]
max-complexity = 12